### ISSUE TITLE
Support for parsing RGBA color specifiation

### ISSUE THREAD

**Issue by theHamsta** [jrmoulton/tree-sitter-slint#1]
I just tried out slint today for the first time (so not an expert). But I think that slint support specifying colors in RBGA format 
https://github.com/slint-ui/slint/blob/c91e49a5552de141e4c59e124f4a75a063e2f99c/examples/slide_puzzle/slide_puzzle.slint#L164

At the moment, this repo just supports parsing colors with 3 or 6 characters receptively https://github.com/jrmoulton/tree-sitter-slint/blob/0d4dda94f96623302dfc234e06be62a5717f47da/grammar.js#L560-L559

**Comment by jrmoulton** [comment]
Thanks for the issue!

Interesting yeah support for that should be added and that would be the place. 

I can merge a PR for that anytime or I'll get a quick fix done in a few days.

**Comment by jrmoulton** [comment]
Fixed in f09b6ea6b0b604acf9d909df781fce36db0717fd !
